import java.awt.Dimension;
import java.sql.CallableStatement;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;

import javax.swing.table.DefaultTableModel;

import oracle.jdbc.OracleType;
import oracle.jdbc.OracleTypes;
import oracle.jdbc.pool.OracleDataSource;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import java.awt.TextArea;
import java.awt.TextField;
import javax.swing.JButton;
import java.awt.Color;
import javax.swing.JScrollPane;
import javax.swing.UIManager;

/**
 * Homepage is a classs which creates the gui of the Retail Business management
 * system
 * 
 * @author Debashish
 */
public class HomePage extends javax.swing.JFrame {

	static Connection conn = null;
	static ResultSet rs = null;
	

	/**
	 * Constructor to connect to the oracle database
	 * 
	 */
	public HomePage() {
		setMinimumSize(new Dimension(1200, 800));
		initComponents();
		OracleDataSource ds;
		try {
			ds = new oracle.jdbc.pool.OracleDataSource();
			ds.setURL("jdbc:oracle:thin:@castor.cc.binghamton.edu:1521:acad111");
			conn = ds.getConnection("dmajumd2", "Dragonballz1234");
			
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
		showPanel.setVisible(true);
		savingpurchasePanel.setVisible(false);
		addCustPanel.setVisible(false);
		addPurPanel.setVisible(false);
		DeletePurchasePanel.setVisible(false);
		MonthSalesPanel.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 102, 102));
		setMaximumSize(new java.awt.Dimension(1200, 800));
		getContentPane().setLayout(null);

		jPanel1 = new javax.swing.JPanel();
		ShowEntities = new javax.swing.JButton();
		ShowEntities.setBackground(UIManager.getColor("Button.background"));
		SavingPurchase = new javax.swing.JButton();
		AddCustomers = new javax.swing.JButton();
		AddPurchase = new javax.swing.JButton();
		DeletPurchase = new javax.swing.JButton();
		SavingPurchase1 = new javax.swing.JButton();

		jPanel1.setBackground(new java.awt.Color(153, 153, 153));

		ShowEntities.setText("Show Entities");
		ShowEntities.setRequestFocusEnabled(false);
		ShowEntities.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ShowEntitiesActionPerformed(evt);
			}
		});

		SavingPurchase.setText("Saving Purchase");
		SavingPurchase.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SavingPurchaseActionPerformed(evt);
			}
		});

		AddCustomers.setText("Add Customer");
		AddCustomers.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AddCustomersActionPerformed(evt);
			}
		});

		AddPurchase.setText("Add Purchase");
		AddPurchase.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AddPurchaseActionPerformed(evt);
			}
		});

		DeletPurchase.setText("Delete Purchase");
		DeletPurchase.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DeletPurchaseActionPerformed(evt);
			}
		});

		SavingPurchase1.setText("Monthly Sales Activites");
		SavingPurchase1.setToolTipText("");
		SavingPurchase1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SavingPurchase1ActionPerformed(evt);
			}
		});
		showPanel = new javax.swing.JPanel();
		ShowallButtonsPanel = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		showTable = new javax.swing.JTable();
		tablePanel = new javax.swing.JPanel();
		employeeButton = new javax.swing.JButton();
		employeeButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				ShowTables st = new ShowTables();
				String proc = "{call rbms_package.display_employees( ? )}";
				ResultSet rs = st.returnTables(conn, proc);
				ConvertToJtable ct = new ConvertToJtable();
				DefaultTableModel model = (DefaultTableModel) showTable.getModel();
				model.setRowCount(0);
				showTable.setModel(model);
				model = ct.ConverttoTable(model, rs);
				showTable.setModel(model);

			}
		});

		CustButton = new javax.swing.JButton();
		ProductsButton = new javax.swing.JButton();
		discountsButton = new javax.swing.JButton();
		SuppliersButton = new javax.swing.JButton();
		SuppliersButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				ShowTables st = new ShowTables();
				String proc = "{call rbms_package.display_suppliers( ? )}";
				ResultSet rs = st.returnTables(conn, proc);
				ConvertToJtable ct = new ConvertToJtable();
				DefaultTableModel model = (DefaultTableModel) showTable.getModel();
				model.setRowCount(0);
				showTable.setModel(model);
				model = ct.ConverttoTable(model, rs);
				showTable.setModel(model);
			}
		});
		suppliesButton = new javax.swing.JButton();
		suppliesButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				ShowTables st = new ShowTables();
				String proc = "{call rbms_package.display_supplies( ? )}";
				ResultSet rs = st.returnTables(conn, proc);
				ConvertToJtable ct = new ConvertToJtable();
				DefaultTableModel model = (DefaultTableModel) showTable.getModel();
				model.setRowCount(0);
				showTable.setModel(model);
				model = ct.ConverttoTable(model, rs);
				showTable.setModel(model);
			}
		});
		purchasesButton = new javax.swing.JButton();

		showPanel.setBackground(new java.awt.Color(204, 204, 204));

		ShowallButtonsPanel.setBackground(new java.awt.Color(153, 153, 153));

		showTable.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledText"));
		showTable
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(showTable);

		javax.swing.GroupLayout ShowallButtonsPanelLayout = new javax.swing.GroupLayout(ShowallButtonsPanel);
		ShowallButtonsPanel.setLayout(ShowallButtonsPanelLayout);
		ShowallButtonsPanelLayout.setHorizontalGroup(
				ShowallButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(ShowallButtonsPanelLayout.createSequentialGroup().addGap(14, 14, 14)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		ShowallButtonsPanelLayout
				.setVerticalGroup(
						ShowallButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(ShowallButtonsPanelLayout.createSequentialGroup().addGap(23, 23, 23)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(15, Short.MAX_VALUE)));

		tablePanel.setBackground(new java.awt.Color(153, 153, 153));

		employeeButton.setText("Employees");

		CustButton.setText("Customers");
		CustButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CustButtonActionPerformed(evt);
			}
		});

		ProductsButton.setText("Products");
		ProductsButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ProductsButtonActionPerformed(evt);
			}
		});

		discountsButton.setText("Discounts");
		discountsButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				discountsButtonActionPerformed(evt);
			}
		});

		SuppliersButton.setText("Suppliers");

		suppliesButton.setText("Supplies");

		purchasesButton.setText("Purchases");
		purchasesButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				purchasesButtonActionPerformed(evt);
			}
		});

		JButton btnNewButton = new JButton("Logs");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				ShowTables st = new ShowTables();
				String proc = "{call rbms_package.display_logs( ? )}";
				ResultSet rs = st.returnTables(conn, proc);
				ConvertToJtable ct = new ConvertToJtable();
				DefaultTableModel model = (DefaultTableModel) showTable.getModel();
				model.setRowCount(0);
				showTable.setModel(model);
				model = ct.ConverttoTable(model, rs);
				showTable.setModel(model);
			}
		});
		DeletePurchasePanel = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		pid1 = new javax.swing.JTextField();
		SavePurchaseButton1 = new javax.swing.JButton();
		SavePurchaseButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				String proc = "{call rbms_package.delete_purchase( ?, ?, ?)}";
				try {
					CallableStatement cb = conn.prepareCall(proc);
					cb.setString(1, pid1.getText().toString());
					cb.registerOutParameter(2, OracleType.VARCHAR2);
					cb.registerOutParameter(3, OracleType.VARCHAR2);

					cb.executeUpdate();

					String status = cb.getString(3);
					String error = cb.getString(2);
					if (error == null) {
						JOptionPane.showMessageDialog(null, status);
					} else {
						JOptionPane.showMessageDialog(null, error);
					}

				} catch (SQLException e1) {

					JOptionPane.showMessageDialog(null, "Please enter valid numeric Purchase ID");
				}

			}
		});
		MonthSalesPanel = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		purIdTextBox1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		SavePurchase1 = new javax.swing.JButton();

		MonthSalesPanel.setBackground(new java.awt.Color(204, 204, 204));

		jPanel6.setBackground(new java.awt.Color(153, 153, 153));

		jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
		jLabel3.setText("Employee ID (eg: e01)");

		SavePurchase1.setBackground(UIManager.getColor("Button.background"));
		SavePurchase1.setText("Report Total Monthly Saving");
		SavePurchase1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SavePurchase1ActionPerformed(evt);
			}
		});
		addCustPanel = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		cid = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		SaveCustomer = new javax.swing.JButton();
		SaveCustomer.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				String proc = "{call rbms_package.add_customers( ?, ?, ?, ? )}";
				try {
					int cid_count = 0;
					String status = "";

					CallableStatement cb = conn.prepareCall(proc);
					cb.setString(1, cid.getText().toString());
					cb.setString(2, jTextField2.getText().toString());
					cb.setString(3, jTextField3.getText().toString());
					cb.registerOutParameter(4, OracleType.VARCHAR2);

					cid_count = cid.getText().length();
					int name_count = jTextField2.getText().length();
					int tele_count = jTextField3.getText().length();

					if (cid_count == 0 || name_count == 0 || tele_count == 0) {
						JOptionPane.showMessageDialog(null, " Please enter all the details ");
					} else {
						if ((cid_count > 4 || cid_count < 4) || (tele_count != 12)) {
							// && name_count > 15 && tele_count != 12 ) {
							JOptionPane.showMessageDialog(null, " Entered customer details are wrong ");
						} else {
							cb.executeUpdate();
							status = cb.getString(4);
							if (status == null) {
								JOptionPane.showMessageDialog(null, "Customer Added Successfully");
							} else {
								JOptionPane.showMessageDialog(null, status);
							}
						}
					}

				} catch (SQLException e) {

					e.printStackTrace();
				}
			}
		});

		addCustPanel.setBackground(new java.awt.Color(204, 204, 204));

		jPanel2.setBackground(new java.awt.Color(153, 153, 153));

		jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Customer ID (eg: c001)");

		jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("Customer Name (max 15 char)");

		jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("Customer Phone Number (eg: 000-000-0000)");

		cid.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cidActionPerformed(evt);
			}
		});
		addPurPanel = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		eid = new javax.swing.JTextField();
		pid = new javax.swing.JTextField();
		purchasecis = new javax.swing.JTextField();
		SavePurchaseButton = new javax.swing.JButton();
		SavePurchaseButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String proc = "{call rbms_package.add_purchase( ?, ?, ?, ?, ?, ?)}";
				try {

					Statement stmt = conn.createStatement();
					CallableStatement cb = conn.prepareCall(proc);
					cb.setString(1, eid.getText().toString());
					cb.setString(2, pid.getText().toString());
					cb.setString(3, purchasecis.getText().toString());
					cb.setString(4, qty.getText().toString());

					cb.registerOutParameter(5, OracleType.VARCHAR2);
					cb.registerOutParameter(6, OracleType.VARCHAR2);

					int eid_count = eid.getText().length();
					int pid_count = pid.getText().length();
					int cid_count = purchasecis.getText().length();
					// String qty_count = qty.getString(4);
					// cb.registerOutParameter(4, qty.getSt.VARCHAR2);
					// int qty = cb.getInt(4);
					int qty1 = Integer.parseInt(qty.getText());
					String pidval = pid.getText();

					int old_qty = 0;
					int thresh_val = 0;

					rs = stmt.executeQuery("SELECT QOH, QOH_THRESHOLD FROM products where pid='" + pidval + "'");

					while (rs.next()) {
						old_qty = Integer.parseInt(rs.getString(1));
						thresh_val = Integer.parseInt(rs.getString(2));
					}
					int temp_qty = old_qty - qty1;

					if (eid_count != 3 || pid_count > 4 || cid_count > 4 || qty1 <= 0) {
						JOptionPane.showMessageDialog(null, "Invalid details");
					} else {

						cb.executeUpdate();

						String status = cb.getString(5);
						String error = cb.getString(6);

						if (error == null) {
							JOptionPane.showMessageDialog(null, status);

							if (status.equals("Purchase Successful")) {
								//System.out.println("hello");
								if (temp_qty < thresh_val) {
									JOptionPane.showMessageDialog(null,
											"Quantity on hand(qoh) is below the required threshold and new supply is required");
									int final_qty = 10 + thresh_val + 1 + temp_qty;
									JOptionPane.showMessageDialog(null, "New value of qoh: " + final_qty);
								}
							}

						} else {
							JOptionPane.showMessageDialog(null, error);
						}
					}

				} catch (SQLException e1) {

					e1.printStackTrace();
				}

			}
		});
		jLabel11 = new javax.swing.JLabel();
		qty = new javax.swing.JTextField();

		addPurPanel.setBackground(new java.awt.Color(204, 204, 204));

		jPanel3.setBackground(new java.awt.Color(153, 153, 153));

		jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("Employee ID (eg: e01)");

		jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("Product ID (eg: p001)");

		jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("Customer ID (eg: c001)");

		eid.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				eidActionPerformed(evt);
			}
		});
		savingpurchasePanel = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		purIdTextBox = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		SavePurchase = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		
				savingpurchasePanel.setBackground(new java.awt.Color(204, 204, 204));
				
						jPanel5.setBackground(new java.awt.Color(153, 153, 153));
						
								jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
								jLabel1.setText("Purchase ID (eg:100001)");
								
										SavePurchase.setText("Report Total Purchase Saving");
										SavePurchase.addActionListener(new java.awt.event.ActionListener() {
											public void actionPerformed(java.awt.event.ActionEvent evt) {
												SavePurchaseActionPerformed(evt);
											}
										});
										
												jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
												jLabel2.setText("Message :");
												
														javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
														jPanel5.setLayout(jPanel5Layout);
														jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(jPanel5Layout.createSequentialGroup().addGroup(jPanel5Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel5Layout.createSequentialGroup().addGap(88, 88, 88).addGroup(jPanel5Layout
																				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(jPanel5Layout.createSequentialGroup().addComponent(jLabel1).addGap(89, 89, 89)
																						.addComponent(purIdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 263,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(jLabel2)))
																		.addGroup(jPanel5Layout.createSequentialGroup().addGap(146, 146, 146).addComponent(SavePurchase,
																				javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addContainerGap(129, Short.MAX_VALUE)));
														jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(jPanel5Layout.createSequentialGroup().addGap(31, 31, 31)
																		.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(purIdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jLabel1))
																		.addGap(57, 57, 57)
																		.addComponent(SavePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 57,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(61, 61, 61).addComponent(jLabel2).addContainerGap(260, Short.MAX_VALUE)));
														
																javax.swing.GroupLayout savingpurchasePanelLayout = new javax.swing.GroupLayout(savingpurchasePanel);
																savingpurchasePanel.setLayout(savingpurchasePanelLayout);
																savingpurchasePanelLayout.setHorizontalGroup(
																		savingpurchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(savingpurchasePanelLayout.createSequentialGroup().addGap(115, 115, 115)
																						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addContainerGap(125, Short.MAX_VALUE)));
																savingpurchasePanelLayout.setVerticalGroup(
																		savingpurchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(savingpurchasePanelLayout.createSequentialGroup().addGap(68, 68, 68)
																						.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addContainerGap(153, Short.MAX_VALUE)));
																
																		getContentPane().add(savingpurchasePanel);
																		savingpurchasePanel.setBounds(202, 0, 907, 751);

		SavePurchaseButton.setText("Add");

		jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("Quantity (greater than 0)");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel3Layout
				.createSequentialGroup().addGap(115)
				.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING, false)
						.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel11)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(qty, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel9)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pid, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel8).addGap(174)
								.addComponent(eid, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel10)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(purchasecis, GroupLayout.PREFERRED_SIZE, 263,
										GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(122, Short.MAX_VALUE))
				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap(408, Short.MAX_VALUE)
						.addComponent(SavePurchaseButton, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
						.addGap(251)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(96)
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING).addComponent(jLabel8)
								.addComponent(eid, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
						.addGap(59)
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel9, Alignment.TRAILING).addComponent(pid, Alignment.TRAILING,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(58)
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING).addComponent(jLabel10)
								.addComponent(purchasecis, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel11, Alignment.TRAILING).addComponent(qty, Alignment.TRAILING,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(62)
						.addComponent(SavePurchaseButton, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
						.addGap(127)));
		jPanel3.setLayout(jPanel3Layout);

		javax.swing.GroupLayout addPurPanelLayout = new javax.swing.GroupLayout(addPurPanel);
		addPurPanel.setLayout(addPurPanelLayout);
		addPurPanelLayout
				.setHorizontalGroup(addPurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(addPurPanelLayout.createSequentialGroup().addGap(73, 73, 73)
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(73, Short.MAX_VALUE)));
		addPurPanelLayout
				.setVerticalGroup(addPurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(addPurPanelLayout.createSequentialGroup().addGap(37, 37, 37)
								.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(101, Short.MAX_VALUE)));

		getContentPane().add(addPurPanel);
		addPurPanel.setBounds(206, 0, 910, 749);

		SaveCustomer.setText("Save");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout
				.createSequentialGroup().addGap(115)
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false)
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel6)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel5).addGap(174)
								.addComponent(cid, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel7)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 263,
										GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(122, Short.MAX_VALUE))
				.addGroup(Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addContainerGap(401, Short.MAX_VALUE)
								.addComponent(SaveCustomer, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
								.addGap(258)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(96)
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING).addComponent(jLabel5)
								.addComponent(cid, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
						.addGap(59)
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel6, Alignment.TRAILING)
								.addComponent(jTextField2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(58)
						.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING).addComponent(jLabel7)
								.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(93)
						.addComponent(SaveCustomer, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(183, Short.MAX_VALUE)));
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout addCustPanelLayout = new javax.swing.GroupLayout(addCustPanel);
		addCustPanel.setLayout(addCustPanelLayout);
		addCustPanelLayout
				.setHorizontalGroup(addCustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(addCustPanelLayout.createSequentialGroup().addGap(71, 71, 71)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(74, Short.MAX_VALUE)));
		addCustPanelLayout
				.setVerticalGroup(addCustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(addCustPanelLayout.createSequentialGroup().addGap(37, 37, 37)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(101, Short.MAX_VALUE)));

		getContentPane().add(addCustPanel);
		addCustPanel.setBounds(201, 0, 910, 749);

		scrollPane = new JScrollPane();

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel6Layout
				.createSequentialGroup()
				.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup().addGap(129).addComponent(scrollPane,
								GroupLayout.PREFERRED_SIZE, 628, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel6Layout.createSequentialGroup().addGap(115).addComponent(jLabel3).addGap(89)
								.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(SavePurchase1, GroupLayout.PREFERRED_SIZE, 269,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(purIdTextBox1, GroupLayout.PREFERRED_SIZE, 263,
												GroupLayout.PREFERRED_SIZE))))
				.addContainerGap(880, Short.MAX_VALUE)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup().addGap(112)
								.addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(purIdTextBox1, GroupLayout.PREFERRED_SIZE, 40,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3))
								.addGap(109)
								.addComponent(SavePurchase1, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
								.addGap(115)
								.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
								.addContainerGap(58, Short.MAX_VALUE)));

		table = new JTable();
		scrollPane.setViewportView(table);
		jPanel6.setLayout(jPanel6Layout);

		javax.swing.GroupLayout MonthSalesPanelLayout = new javax.swing.GroupLayout(MonthSalesPanel);
		MonthSalesPanelLayout.setHorizontalGroup(MonthSalesPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, MonthSalesPanelLayout
						.createSequentialGroup().addContainerGap(154, Short.MAX_VALUE).addComponent(jPanel6,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGap(33)));
		MonthSalesPanelLayout
				.setVerticalGroup(MonthSalesPanelLayout.createParallelGroup(Alignment.LEADING)
						.addGroup(MonthSalesPanelLayout.createSequentialGroup().addContainerGap().addComponent(jPanel6,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addContainerGap(163, Short.MAX_VALUE)));
		MonthSalesPanel.setLayout(MonthSalesPanelLayout);

		getContentPane().add(MonthSalesPanel);
		MonthSalesPanel.setBounds(202, 0, 910, 749);

		DeletePurchasePanel.setBackground(new java.awt.Color(204, 204, 204));

		jPanel4.setBackground(new java.awt.Color(153, 153, 153));

		jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("Purchase ID (eg: 100011)");

		SavePurchaseButton1.setText("Delete");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel4Layout
				.createSequentialGroup()
				.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addGap(174).addComponent(jLabel13).addGap(120)
								.addComponent(pid1, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel4Layout.createSequentialGroup().addGap(279).addComponent(SavePurchaseButton1,
								GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(122, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(
						jPanel4Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(181)
										.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(pid1, GroupLayout.PREFERRED_SIZE, 48,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel13))
										.addGap(65).addComponent(SavePurchaseButton1, GroupLayout.PREFERRED_SIZE, 44,
												GroupLayout.PREFERRED_SIZE)
										.addContainerGap(275, Short.MAX_VALUE)));
		jPanel4.setLayout(jPanel4Layout);

		javax.swing.GroupLayout DeletePurchasePanelLayout = new javax.swing.GroupLayout(DeletePurchasePanel);
		DeletePurchasePanel.setLayout(DeletePurchasePanelLayout);
		DeletePurchasePanelLayout.setHorizontalGroup(
				DeletePurchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						DeletePurchasePanelLayout.createSequentialGroup().addContainerGap(54, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(76, 76, 76)));
		DeletePurchasePanelLayout.setVerticalGroup(
				DeletePurchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(DeletePurchasePanelLayout.createSequentialGroup().addGap(30, 30, 30)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(108, Short.MAX_VALUE)));

		getContentPane().add(DeletePurchasePanel);
		DeletePurchasePanel.setBounds(197, 0, 920, 749);

		javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
		tablePanelLayout.setHorizontalGroup(tablePanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(tablePanelLayout.createSequentialGroup().addGap(33).addComponent(employeeButton)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(CustButton)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(ProductsButton)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(discountsButton)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(SuppliersButton)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(suppliesButton)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(purchasesButton)
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(btnNewButton)
						.addContainerGap(156, Short.MAX_VALUE)));
		tablePanelLayout.setVerticalGroup(tablePanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(tablePanelLayout.createSequentialGroup().addGap(32)
						.addGroup(tablePanelLayout.createParallelGroup(Alignment.BASELINE).addComponent(btnNewButton)
								.addComponent(purchasesButton).addComponent(suppliesButton)
								.addComponent(SuppliersButton).addComponent(discountsButton)
								.addComponent(ProductsButton).addComponent(CustButton).addComponent(employeeButton))
						.addContainerGap(39, Short.MAX_VALUE)));
		tablePanel.setLayout(tablePanelLayout);

		javax.swing.GroupLayout showPanelLayout = new javax.swing.GroupLayout(showPanel);
		showPanel.setLayout(showPanelLayout);
		showPanelLayout.setHorizontalGroup(showPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(showPanelLayout.createSequentialGroup().addGap(22, 22, 22).addGroup(showPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(ShowallButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(showPanelLayout.createSequentialGroup()
								.addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap()));
		showPanelLayout.setVerticalGroup(showPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(showPanelLayout.createSequentialGroup().addGap(48, 48, 48)
						.addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(ShowallButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(40, 40, 40)));

		getContentPane().add(showPanel);
		showPanel.setBounds(204, 0, 910, 709);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
				.createSequentialGroup()
				.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(Alignment.TRAILING, jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(
										SavingPurchase1, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE))
								.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup().addContainerGap()
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
												.addComponent(SavingPurchase, Alignment.LEADING,
														GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(ShowEntities, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
														160, Short.MAX_VALUE))))
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(AddPurchase, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(AddCustomers, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 158,
												Short.MAX_VALUE))))
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(DeletPurchase)))
				.addContainerGap(18, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(70).addComponent(ShowEntities).addGap(38)
						.addComponent(SavingPurchase).addGap(56).addComponent(SavingPurchase1).addGap(47)
						.addComponent(AddCustomers).addGap(38).addComponent(AddPurchase).addGap(48)
						.addComponent(DeletPurchase).addContainerGap(278, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		getContentPane().add(jPanel1);
		jPanel1.setBounds(0, 0, 196, 749);

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Exit");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void ShowEntitiesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ShowEntitiesActionPerformed
		// TODO add your handling code here:

		showPanel.setVisible(true);
		savingpurchasePanel.setVisible(false);
		addCustPanel.setVisible(false);
		addPurPanel.setVisible(false);
		DeletePurchasePanel.setVisible(false);
		MonthSalesPanel.setVisible(false);

		ConvertToJtable ct = new ConvertToJtable();

	}// GEN-LAST:event_ShowEntitiesActionPerformed

	private void CustButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CustButtonActionPerformed
		// TODO add your handling code here:

		ShowTables st = new ShowTables();
		String proc = "{call rbms_package.display_customers( ? )}";
		ResultSet rs = st.returnTables(conn, proc);
		ConvertToJtable ct = new ConvertToJtable();
		DefaultTableModel model = (DefaultTableModel) showTable.getModel();
		model.setRowCount(0);
		showTable.setModel(model);
		model = ct.ConverttoTable(model, rs);
		showTable.setModel(model);

	}// GEN-LAST:event_CustButtonActionPerformed

	private void purchasesButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_purchasesButtonActionPerformed
		ShowTables st = new ShowTables();
		String proc = "{call rbms_package.display_purchases( ? )}";
		ResultSet rs = st.returnTables(conn, proc);
		ConvertToJtable ct = new ConvertToJtable();
		DefaultTableModel model = (DefaultTableModel) showTable.getModel();
		model.setRowCount(0);
		showTable.setModel(model);
		model = ct.ConverttoTable(model, rs);
		showTable.setModel(model);
	}// GEN-LAST:event_purchasesButtonActionPerformed

	private void ProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ProductsButtonActionPerformed
		ShowTables st = new ShowTables();
		String proc = "{call rbms_package.display_products( ? )}";
		ResultSet rs = st.returnTables(conn, proc);
		ConvertToJtable ct = new ConvertToJtable();
		DefaultTableModel model = (DefaultTableModel) showTable.getModel();
		model.setRowCount(0);
		showTable.setModel(model);
		model = ct.ConverttoTable(model, rs);
		showTable.setModel(model);
	}// GEN-LAST:event_ProductsButtonActionPerformed

	private void discountsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_discountsButtonActionPerformed
		ShowTables st = new ShowTables();
		String proc = "{call rbms_package.display_discounts( ? )}";
		ResultSet rs = st.returnTables(conn, proc);
		ConvertToJtable ct = new ConvertToJtable();
		DefaultTableModel model = (DefaultTableModel) showTable.getModel();
		model.setRowCount(0);
		showTable.setModel(model);
		model = ct.ConverttoTable(model, rs);
		showTable.setModel(model);
	}// GEN-LAST:event_discountsButtonActionPerformed

	private void SavePurchaseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SavePurchaseActionPerformed
		ShowTables st = new ShowTables();

		String proc = "{? = call rbms_package.purchase_saving( ? )}";
		try {
			// String status = "";
			CallableStatement cb = conn.prepareCall(proc);
			cb.registerOutParameter(1, OracleTypes.NUMBER);
			cb.setString(2, purIdTextBox.getText().toString());
			int pur_count = purIdTextBox.getText().length();

			if (pur_count > 6 || pur_count < 6) {
				JOptionPane.showMessageDialog(null, "Invalid Purchase ID");

			} else {
				cb.execute();
				double n = cb.getDouble(1);
				if (n == -1) {
					JOptionPane.showMessageDialog(null, "Purchase ID not available");
				} else {
					jLabel2.setText("Total purchase saving is " + n);
				}
			}
			// conn.close();
		} catch (SQLException e) {

			// e.printStackTrace();
			JOptionPane.showMessageDialog(null, "Invalid Purchase ID");
		}

		// ResultSet rs=st.returnTables(conn, proc);

	}// GEN-LAST:event_SavePurchaseActionPerformed

	private void SavingPurchaseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SavingPurchaseActionPerformed
		// TODO add your handling code here:
		showPanel.setVisible(false);
		savingpurchasePanel.setVisible(true);
		addCustPanel.setVisible(false);
		addPurPanel.setVisible(false);
		DeletePurchasePanel.setVisible(false);
		MonthSalesPanel.setVisible(false);

	}// GEN-LAST:event_SavingPurchaseActionPerformed

	private void SavingPurchase1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SavingPurchase1ActionPerformed
		// TODO add your handling code here:
		showPanel.setVisible(false);
		savingpurchasePanel.setVisible(false);
		addCustPanel.setVisible(false);
		addPurPanel.setVisible(false);
		DeletePurchasePanel.setVisible(false);
		MonthSalesPanel.setVisible(true);

	}// GEN-LAST:event_SavingPurchase1ActionPerformed

	private void SavePurchase1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SavePurchase1ActionPerformed

		// ShowTables st=new ShowTables();

		// ResultSet rs=st.returnTables(conn, proc);
		// ConvertToJtable ct=new ConvertToJtable();
		// DefaultTableModel model=(DefaultTableModel)showTable.getModel();
		// model.setRowCount(0);
		// showTable.setModel(model);
		// model=ct.ConverttoTable(model, rs);
		// showTable.setModel(model);

		String proc = "{call rbms_package.monthly_sale_activities( ?, ?, ?)}";
		try {
			// ShowTables st=new ShowTables();
			CallableStatement cb = conn.prepareCall(proc);
			cb.setString(1, purIdTextBox1.getText().toString());
			String status = "";
			cb.registerOutParameter(2, OracleType.VARCHAR2);
			cb.registerOutParameter(3, OracleTypes.CURSOR);
			cb.execute();

			int pur_count = purIdTextBox1.getText().length();
			if (pur_count < 3 || pur_count > 3) {
				JOptionPane.showMessageDialog(null, "Invalid Employee ID");
			} else {

				status = cb.getString(2);
				if (status == null) {

					ResultSet rs = (ResultSet) cb.getObject(3);
					ConvertToJtable ct = new ConvertToJtable();
					DefaultTableModel model = (DefaultTableModel) table.getModel();
					model.setRowCount(0);
					table.setModel(model);
					model = ct.ConverttoTable((DefaultTableModel) table.getModel(), rs);
					table.setModel(model);

				} else {
					JOptionPane.showMessageDialog(null, status);
				}
			}

		} catch (SQLException e1) {

			e1.printStackTrace();
		}

	}// GEN-LAST:event_SavePurchase1ActionPerformed

	private void AddCustomersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddCustomersActionPerformed
		// TODO add your handling code here:
		showPanel.setVisible(false);
		savingpurchasePanel.setVisible(false);
		addCustPanel.setVisible(true);
		addPurPanel.setVisible(false);
		DeletePurchasePanel.setVisible(false);
		MonthSalesPanel.setVisible(false);

	}// GEN-LAST:event_AddCustomersActionPerformed

	private void AddPurchaseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddPurchaseActionPerformed
		// TODO add your handling code here:

		showPanel.setVisible(false);
		savingpurchasePanel.setVisible(false);
		addCustPanel.setVisible(false);
		addPurPanel.setVisible(true);
		DeletePurchasePanel.setVisible(false);
		MonthSalesPanel.setVisible(false);

	}// GEN-LAST:event_AddPurchaseActionPerformed

	private void DeletPurchaseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DeletPurchaseActionPerformed
		// TODO add your handling code here:
		showPanel.setVisible(false);
		savingpurchasePanel.setVisible(false);
		addCustPanel.setVisible(false);
		addPurPanel.setVisible(false);
		DeletePurchasePanel.setVisible(true);
		MonthSalesPanel.setVisible(false);

	}// GEN-LAST:event_DeletPurchaseActionPerformed

	private void cidActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cidActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cidActionPerformed

	private void eidActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_eidActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_eidActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomePage().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton AddCustomers;
	private javax.swing.JButton AddPurchase;
	private javax.swing.JButton CustButton;
	private javax.swing.JButton DeletPurchase;
	private javax.swing.JPanel DeletePurchasePanel;
	private javax.swing.JPanel MonthSalesPanel;
	private javax.swing.JButton ProductsButton;
	private javax.swing.JButton SaveCustomer;
	private javax.swing.JButton SavePurchase;
	private javax.swing.JButton SavePurchase1;
	private javax.swing.JButton SavePurchaseButton;
	private javax.swing.JButton SavePurchaseButton1;
	private javax.swing.JButton SavingPurchase;
	private javax.swing.JButton SavingPurchase1;
	private javax.swing.JButton ShowEntities;
	private javax.swing.JPanel ShowallButtonsPanel;
	private javax.swing.JButton SuppliersButton;
	private javax.swing.JPanel addCustPanel;
	private javax.swing.JPanel addPurPanel;
	private javax.swing.JTextField cid;
	private javax.swing.JButton discountsButton;
	private javax.swing.JTextField eid;
	private javax.swing.JButton employeeButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField pid;
	private javax.swing.JTextField pid1;
	private javax.swing.JTextField purIdTextBox;
	private javax.swing.JTextField purIdTextBox1;
	private javax.swing.JTextField purchasecis;
	private javax.swing.JButton purchasesButton;
	private javax.swing.JTextField qty;
	private javax.swing.JPanel savingpurchasePanel;
	private javax.swing.JPanel showPanel;
	private javax.swing.JTable showTable;
	private javax.swing.JButton suppliesButton;
	private javax.swing.JPanel tablePanel;
	private JScrollPane scrollPane;
	private JTable table;
}
